config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :api_user_email, only: [:edit]
  resources :api_user_name, only: [:edit]
  resources :api_user_password, only: [:edit]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, t("about")) %>
  <div class="about">
    <h1><%= t("about") %></h1>
    <p><%= t("about_html") %></p>
  </div>

app/views/static_pages/contact.html.erb
<% provide(:title, t("contact")) %>
<div class="contact">
    <h1><%= t("contact") %></h1>
    <p><%= t("contact_html") %></p>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, t("help")) %>
<div class="help">
  <h1><%= t("help") %></h1>
  <p><%= t("help_html") %></p>
</div>

app/views/static_pages/home.html.erb
<!-- <div class="center jumbotron"> -->
<div class="header">
    <div class="text-box">
        <h1 class="heading-primary">
            <span class = heading-primary-main><%= t('welcome') %></span>
            <span class = heading-primary-sub><%= t('greeting_html')%></span>
        </h1>

        <%= link_to t("signupNow") , signup_path, class: "btn btn-theme btn-animated" %>
    </div>
</div>
</br>
<%= link_to image_tag("rails.png", alt: "Rails logo"),
            'http://rubyonrails.org/' %>