config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'users/new'

  root             'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :api_user_email, only: [:edit]
  resources :api_user_name, only: [:edit]
  resources :api_user_password, only: [:edit]

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <%= t("footer_html") %>
  </small>
  <nav>
    <ul>
      <li><%= link_to t("about"),   about_path %></li>
      <li><%= link_to t("contact"), contact_path %></li>
      <li><a href="http://news.railstutorial.org/"><%= t("news") %></a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container">
    <!-- <nav> -->
      <%= render 'layouts/menu' %>
    <!-- </nav> -->
  </div>
</header>

app/views/layouts/_menu.html.erb
    <!--<nav class="navbar navbar-default">
     <div class="container-fluid"> -->  
      <%= render 'layouts/navbar-header' %>
      <%= render 'layouts/navbar-body' %>
    <!-- </div>   
    </nav>-->

app/views/layouts/_navbar-body.erb
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right fa-ul">
            <li><%= link_to t("home"), root_path, :class => 'fa fa-home' %></li>
            <li><%= link_to t("help"), help_path, :class => 'fa fa-info' %></li>
            <%= render 'layouts/navbar-user-account' %>
            <li><%= link_to "  中文版", :controller => controller_name, :action => action_name, :locale => "zh-HK"%></li>
            <li><%= link_to "  English", :controller => controller_name, :action => action_name, :locale => "en" %></li>
          </ul>
        </div>

app/views/layouts/_navbar-header.erb
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#"><%= link_to t("sampleApp"), root_path, id: "logo" %></a>
        </div>

app/views/layouts/_navbar-user-account.erb
            <% if logged_in? %>
              <li><%= link_to t("usersMenu"), users_path, :class => 'fa fa-users' %></li>
              <li class="dropdown">
                <a href="#" class="dropdown-toggle fa fa-user-plus" data-toggle="dropdown">
                  <%= t("account") %> <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to t("profile"), current_user, :class => 'fa fa-user' %></li>
                  <li><%= link_to t("settings"), edit_user_path(current_user), :class => 'fa fa-user-circle' %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to t("logoutNow"), logout_path, method: "delete", :class => 'fa fa-sign-out' %>
                  </li>
                </ul>
              </li>
            <% else %>
              <li><%= link_to t("loginNow"), login_path, :class => 'fa fa-sign-in' %></li>
            <% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">
  <!-- Mobile meta setting -->
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>